spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/testdb?useSSL=false&serverTimezone=Asia/Seoul
    driver-class-name: org.mariadb.jdbc.Driver
    username: testuser
    password: test1234
    hikari:
      minimum-idle: 5         # ?? ??? ?
      maximum-pool-size: 20   # ?? ??? ?
      idle-timeout: 30000     # ??? ???? (ms)

  jpa:
    hibernate:
      ddl-auto: update  # ??? (?? ?? none)
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect


